### PR TITLE
Feature/forms update login

### PR DESCRIPTION
**Pull request by QuaziBit**
Add/Update/Delete were implemented for the Member, Volunteer, Activities

### CODE REVIEW

**Review by RialJohnson — APPROVED** [review]
Update looks great!

**Review by Rusty89 — APPROVED** [review]
Looks good, thanks Alex

**Comment by Rusty89** [comment]
All those conflicts are due to filename changes, which i can't seem to resolve so I'm going to revert develop back to a previous state then we can try again

**Comment by Rusty89** [comment]
Reopened it, i probably shouldn't have closed, that was my bad.  You guys can keep trying to resolve if you want

**Pull request merged**
