### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by RialJohnson**
Merge Develop to Master for the Beta Release 03/01/2019

### CODE REVIEW

**Comment by QuaziBit** [comment]
Looks good

**Review by QuaziBit — COMMENTED** [review]
Looks good

**Review by Rusty89 — APPROVED** [review]
Resolved the merge conflicts I think, looks good.

**Review by QuaziBit — APPROVED** [review]
Looks like all conflicts were fixed, so it look good to me.

**Pull request merged**
