### PR TITLE
Built Angular App

### PR DESCRIPTION
**Pull request by RialJohnson**
Created Angular App
Converted html/css to typescript files for angular compatibility
Created working SPA routing
Reworked file structure

### CODE REVIEW

**Review by QuaziBit — COMMENTED** [review]
Looks good

**Review by NickHager — APPROVED** [review]
All new files, so we should be good to go without conflicts.

**Review by marinerslakers — APPROVED** [review]
New files so good to go

**Comment by Rusty89** [comment]
Looks good

**Pull request merged**
