### PR TITLE
Feature/delete confirmation

### PR DESCRIPTION
**Pull request by Rusty89**
Added confirmations to deleting members, volunteers and services using built in confirm function.

### CODE REVIEW

**Review by QuaziBit — APPROVED** [review]
Looks Good

**Review by RialJohnson — CHANGES_REQUESTED** [review]
Can you add this to deleting from an involvement as well?

**Comment by Rusty89** [comment]
> Can you add this to deleting from an involvement as well?

Yes, sorry it totally slipped my mind, just added

**Review by RialJohnson — APPROVED** [review]
Thanks for getting this done so quickly!

**Pull request merged**
