### PR TITLE
Volunteer nav and form

### PR DESCRIPTION
**Pull request by NickHager**
I believe this should fix the test issues...

### CODE REVIEW

**Comment by NickHager** [comment]
Issue was making calls like this, [(ngModel)]="volunteers.apt" in the volunteer.component.html file. I thought I would save us time for when we actually set it up in the future, but it was causing the tests to fail.

**Review by RialJohnson — APPROVED** [review]
Cool, thanks for working through the test errors. Everything looks good now. Just so you know, I believe that you can make new commits to the branch (after creating a PR) and the PR should be updated and Travis should test again. You shouldn't need to open/close PRs to make changes to them.

**Comment by NickHager** [comment]
Okay, good to know. I wasn't quite sure how to get the tests to run without a new PR.

**Review by Rusty89 — APPROVED** [review]
Looks good

**Pull request merged**
